# Generated by Django 3.1.4 on 2021-01-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210112_1100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stream',
            table=None,
        ),
    ]
