# Generated by Django 3.1.4 on 2021-01-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='Blog_url',
        ),
    ]
