# Generated by Django 3.1.4 on 2021-01-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210112_1052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
